### PR TITLE
Utilize paper-input error-message when invalid

### PR DESCRIPTION
**Pull request by bpinney**

### CODE REVIEW

**Comment by bpinney** [comment]
I am a part of the Labor Sync organization which signed the CLA, I just added myself to the group. Please check again! Thanks.

**Comment by notwaldorf** [comment]
LGTM! /cc @cdata

**Comment by fabiomocci** [comment]
Hi,

Any plans for this pull to be merged?

Also, this pull implementation auto scrolls the page and sets the focus on the invalid component?

Thanks!

**Comment by bpinney** [comment]
I made no changes which would auto-scroll or auto-focus the invalid input, only utilize paper-input error-message when invalid.

**Comment by notwaldorf** [comment]
Sorry about that! Merged!

**Comment by fabiomocci** [comment]
Thanks @bpinney and @notwaldorf !

About the auto-scroll and auto-foculs when input is invalide, should I open a issue?

**Pull request merged**
