### PR TITLE
Fixes #22

### LINKED ISSUE #22: selectedItemLabel requires label *property* / won't work with just attribute
Since paper-items (a very common use case I would think) don't have a label *property*, the following won't work as expected.  Instead of ``selectedItemLabel`` being "Pizza", it's "Burgers".

```
<paper-dropdown-menu label="Favorite food">
	<paper-menu class="dropdown-content" attr-for-selected="label">
		<paper-item label="Pizza">Burgers</paper-item>
	</paper-menu>
</paper-dropdown-menu>
```

### PR DESCRIPTION
**Pull request by miztroh**
If no label property exists, try label attribute before falling back to textContent.  Added tests.

(added by @bicknellr: Fixes PolymerElements/paper-item#76.)

### CODE REVIEW

**Comment by cdata** [comment]
Thank you for your contribution. I'm going to close this PR for now, since it doesn't have a corresponding issue proposing the design for this feature. Please consult our [contribution guidelines](../blob/master/CONTRIBUTING.md) for help on filing issues and opening PRs in the future!

**Comment by miztroh** [comment]
@cdata Have you looked at issue #22?  That's the issue this is intended to fix.  @notwaldorf marked it as "help wanted".  What am I missing?

**Comment by miztroh** [comment]
This is taken directly from CONTRIBUTING.md:

```markdown
When submitting pull requests, please provide:

 1. **A reference to the corresponding issue** or issues that will be closed by the pull request. Please refer to these issues in the pull request description using the following syntax:

 (For a single issue)
 Fixes #20

 (For multiple issues)
 Fixes #32, fixes #40

 2. **A succinct description of the design** used to fix any related issues. For example:

 This fixes #20 by removing styles that leaked which would cause the page to turn pink whenever `paper-foo` is clicked.

 3. **At least one test for each bug fixed or feature added** as part of the pull request. Pull requests that fix bugs or add features without accompanying tests will not be considered.
```

I believe I have met all of these requirements.

**Comment by miztroh** [comment]
@cdata Will you please reopen?

**Comment by bicknellr** [comment]
(Fixes PolymerElements/paper-item#76.)

**Comment by bicknellr** [comment]
Even more disturbing: I just got an email from GitHub claiming that you made that edit...

**Comment by miztroh** [comment]
That *is* weird.

**Comment by kungufli** [comment]
Any update on this?

**Comment by miztroh** [comment]
@bicknellr @notwaldorf What else is needed for this to get merged?

**Comment by bicknellr** [comment]
Everything looks good, sorry about the delay!

**Pull request merged**
