### PR TITLE
Added verticalAlign and horizontalAlign properties

### PR DESCRIPTION
**Pull request by kevashcraft**
Added properties to pass verticalAlign and horizontalAlign to the paper-menu-button.

### CODE REVIEW

**Comment by flashback2k14** [comment]
+1 this works very well and is highly needed!

**Comment by chunkzer** [comment]
Was just working on this before I noticed there was a PR. Ran into some strange behavior that maybe makes this PR pointless, I can still pass horizontal-align and vertical-align to paper-dropdown-menu despite not having the changes in the PR. I can no longer do so, if I make paper-menu-button have fixed parameters (instead of passing them, a la this PR).

I'm only adding vertical-align and horizontal align to the basic menu on paper-dropdown-menu demo index.html and it works fine for me. 







I attached the modified paper-dropdown-menu demo I'm testing with.

**Comment by cdata** [comment]
This PR is looking good, but it needs a rebase before it can be merged. I'm going to close it for now, but please re-open it after you have performed a rebase!

**Comment by kevashcraft** [comment]
The pass-verticalAlign branch has been rebased but it didn't update the PR. Did I miss a step? It updated on my fork. 73

**Pull request closed without merging**
