### PR TITLE
Update with the Polymer 1.1 style recommendations

### PR DESCRIPTION
**Pull request by abdonrd**

### CODE REVIEW

**Comment by fiws** [comment]
+1

**Comment by rafaeljusto** [comment]
+1

**Comment by abdonrd** [comment]
Re-updated to master! :smiley:

**Comment by abdonrd** [comment]
Re-updated to master! :smiley:

**Comment by abdonrd** [comment]
Rebased with the @notwaldorf changes (#52 and #57)!

**Comment by abdonrd** [comment]
I rebased this veeery old PR. (3 Sep)

@notwaldorf can you validate it? :blush:

**Comment by abdonrd** [comment]
Rebased another time! :)

**Comment by notwaldorf** [comment]
Sorry, this isn't one of my elements, so I didn't look at PRs for it. LGTM.

/cc @cdata

**Comment by abdonrd** [comment]
No problem, thanks @notwaldorf! :gem:

**Pull request merged**
