### PR TITLE
Automatic cleanup!

### PR DESCRIPTION
**Pull request by azakus**

### CODE REVIEW

**Comment by cdata** [comment]
This is a transitive failure due to https://github.com/PolymerLabs/polylint/issues/90 which incorrectly flags `paper-input` as doing something bad.

**Comment by cdata** [comment]
Looks like polymerlabs/polylint#90 is fixed, giving the tests another run.

**Comment by cdata** [comment]
Success! This no longer fails due to Polylint. @azakus can you rebase this PR?

**Comment by azakus** [comment]
Rebased!

**Pull request merged**
