### PR TITLE
Fixes #165: Adds tabindex, fixes focus styles.

### LINKED ISSUE #165: paper-dropdown-menu-light can't be tabbed to by default
By default, `paper-dropdown-menu-light` cannot be tabbed to.

Fiddle: https://jsfiddle.net/a89rd18L/

1. Click the text at the top of the page.
2. Press Tab 4 times.

Expected: tab moves between each dropdown menu.
Actual: only the `paper-dropdown-menu`s can be tabbed to, not the `paper-dropdown-menu-light`s.

Is this because `paper-dropdown-menu-light` doesn't use `IronMenuBehavior`? Are there other attributes or functions of `IronMenuBehavior` that the menu should have?

Chrome 52.0.2743.32

### PR DESCRIPTION
**Pull request by bicknellr**
Adds tabindex to hostAttributes, removes outline from focus style (focus is shown with underline color / size).

### CODE REVIEW

**Comment by e111077** [comment]
LGTM, it even works better than the non-light focusing when tabbing quickly on firefox. (the upper ones are the light version)

image

**Comment by bicknellr** [comment]
I tried it out there and the underline was rendered as only 1px tall, but it wasn't totally missing like the picture above. Weirdly, the position of the bar played an effect here, adjusting `bottom` by a pixel caused it to render as expected (2px); conveniently, it was already 1px too high so I set it to 7.

**Comment by e111077** [comment]
Sorry, I wasn't clear; the light version functions correctly. when tabbing through quickly on Firefox, the light one has the underline appear and disappear. On the non-light version, the underline persists. I completely forgot to file a bug; thanks for the reminder.

**Comment by cdata** [comment]
LGTM 👍

**Comment by bicknellr** [comment]
Woot, tests are working again!

**Pull request merged**
